import type { ObjectDefinition, RoomDefinition, WeaponStats } from "./types"

export const WEAPONS: WeaponStats[] = [
  {
    id: "baseball-bat",
    name: "Baseball bat",
    speed: 0.7,
    baseDamage: 22,
    timingEase: 0.85,
    controlledMultiplier: 2.4,
    locked: false,
  },
  {
    id: "rubber-chicken",
    name: "Rubber chicken",
    speed: 1,
    baseDamage: 14,
    timingEase: 0.7,
    controlledMultiplier: 3.2,
    locked: false,
  },
  {
    id: "sledgehammer",
    name: "Sledgehammer",
    speed: 0.45,
    baseDamage: 35,
    timingEase: 0.6,
    controlledMultiplier: 2.1,
    locked: true,
    unlockHint: "Future unlock",
  },
  {
    id: "frying-pan",
    name: "Frying pan",
    speed: 0.8,
    baseDamage: 18,
    timingEase: 0.75,
    controlledMultiplier: 2.6,
    locked: true,
    unlockHint: "Future unlock",
  },
  {
    id: "boxing-glove",
    name: "Boxing glove",
    speed: 0.9,
    baseDamage: 16,
    timingEase: 0.8,
    controlledMultiplier: 2.8,
    locked: true,
    unlockHint: "Future unlock",
  },
  {
    id: "crowbar",
    name: "Crowbar",
    speed: 0.55,
    baseDamage: 28,
    timingEase: 0.65,
    controlledMultiplier: 2.2,
    locked: true,
    unlockHint: "Future unlock",
  },
]

const officeObjects: ObjectDefinition[] = [
  {
    id: "printer",
    name: "Printer",
    durability: 100,
    scoreValue: 40,
    size: "large",
    color: "#94A3B8",
    accent: "#64748B",
  },
  {
    id: "monitor",
    name: "Monitor",
    durability: 95,
    scoreValue: 38,
    size: "large",
    color: "#1E293B",
    accent: "#38BDF8",
  },
  {
    id: "laptop",
    name: "Laptop",
    durability: 70,
    scoreValue: 30,
    size: "medium",
    color: "#CBD5E1",
    accent: "#38BDF8",
  },
  {
    id: "keyboard",
    name: "Keyboard",
    durability: 55,
    scoreValue: 24,
    size: "medium",
    color: "#27272A",
    accent: "#F4F4F5",
  },
  {
    id: "filing-cabinet",
    name: "Filing cabinet",
    durability: 120,
    scoreValue: 45,
    size: "large",
    color: "#78716C",
    accent: "#A8A29E",
  },
  {
    id: "coffee-machine",
    name: "Coffee machine",
    durability: 80,
    scoreValue: 35,
    size: "medium",
    color: "#57534E",
    accent: "#F97316",
  },
  {
    id: "alarm-clock",
    name: "Alarm clock",
    durability: 45,
    scoreValue: 20,
    size: "small",
    color: "#FBBF24",
    accent: "#EF4444",
  },
  {
    id: "desk-lamp",
    name: "Desk lamp",
    durability: 50,
    scoreValue: 22,
    size: "small",
    color: "#F97316",
    accent: "#FBBF24",
  },
  {
    id: "mug-stack",
    name: "Mug stack",
    durability: 40,
    scoreValue: 18,
    size: "small",
    color: "#FB923C",
    accent: "#38BDF8",
  },
  {
    id: "email-sign",
    name: "This meeting could have been an email",
    durability: 55,
    scoreValue: 25,
    size: "medium",
    color: "#FEF3C7",
    accent: "#DC2626",
  },
]

const kitchenObjects: ObjectDefinition[] = [
  {
    id: "toaster",
    name: "Toaster",
    durability: 65,
    scoreValue: 28,
    size: "medium",
    color: "#A1A1AA",
    accent: "#F97316",
  },
  {
    id: "plates",
    name: "Stack of plates",
    durability: 50,
    scoreValue: 22,
    size: "medium",
    color: "#F5F5F4",
    accent: "#0EA5E9",
  },
  {
    id: "mug",
    name: "Mug",
    durability: 35,
    scoreValue: 15,
    size: "small",
    color: "#FB923C",
    accent: "#FFFFFF",
  },
  {
    id: "blender",
    name: "Blender",
    durability: 90,
    scoreValue: 38,
    size: "medium",
    color: "#E5E5E5",
    accent: "#22C55E",
  },
  {
    id: "saucepan",
    name: "Saucepan",
    durability: 75,
    scoreValue: 32,
    size: "medium",
    color: "#9CA3AF",
    accent: "#111827",
  },
  {
    id: "kitchen-clock",
    name: "Kitchen clock",
    durability: 40,
    scoreValue: 18,
    size: "small",
    color: "#FDE68A",
    accent: "#B45309",
  },
]

const techObjects: ObjectDefinition[] = [
  {
    id: "wifi-router",
    name: "Wi-Fi router",
    durability: 70,
    scoreValue: 30,
    size: "medium",
    color: "#1E293B",
    accent: "#22D3EE",
  },
  {
    id: "old-phone",
    name: "Old mobile phone",
    durability: 45,
    scoreValue: 20,
    size: "small",
    color: "#334155",
    accent: "#A3E635",
  },
  {
    id: "monitor",
    name: "Computer monitor",
    durability: 100,
    scoreValue: 42,
    size: "large",
    color: "#0F172A",
    accent: "#38BDF8",
  },
  {
    id: "keyboard",
    name: "Keyboard",
    durability: 55,
    scoreValue: 24,
    size: "medium",
    color: "#27272A",
    accent: "#F4F4F5",
  },
  {
    id: "loading-spinner",
    name: "Loading spinner display",
    durability: 60,
    scoreValue: 26,
    size: "medium",
    color: "#18181B",
    accent: "#F97316",
  },
  {
    id: "smart-speaker",
    name: "Smart speaker",
    durability: 50,
    scoreValue: 22,
    size: "small",
    color: "#3F3F46",
    accent: "#67E8F9",
  },
]

export const ROOMS: RoomDefinition[] = [
  {
    id: "office-meltdown",
    name: "Office Meltdown",
    description: "Printers, laptops and meeting signs that had it coming.",
    locked: false,
    objects: officeObjects,
  },
  {
    id: "kitchen-chaos",
    name: "Kitchen Chaos",
    description: "Toast, plates and appliances ready for a reset.",
    locked: false,
    objects: kitchenObjects,
  },
  {
    id: "technology-breakdown",
    name: "Technology Breakdown",
    description: "Routers, screens and endless loading loops.",
    locked: false,
    objects: techObjects,
  },
  {
    id: "monday-morning",
    name: "Monday Morning",
    description: "A chaotic desk daydream.",
    locked: true,
    comingLater: true,
    objects: [],
  },
  {
    id: "traffic-nightmare",
    name: "Traffic Nightmare",
    description: "Horns, cones and gridlock energy.",
    locked: true,
    comingLater: true,
    objects: [],
  },
]

export function getRoom(roomId: string): RoomDefinition | undefined {
  return ROOMS.find((r) => r.id === roomId)
}

export function getWeapon(weaponId: string): WeaponStats | undefined {
  return WEAPONS.find((w) => w.id === weaponId)
}

export const BOSS_PRINTER = {
  id: "unbreakable-printer",
  name: "The Unbreakable Printer",
  durability: 280,
  color: "#94A3B8",
  accent: "#EF4444",
}
