import { readFileSync, writeFileSync } from "fs"
import { join } from "path"
import type { Listing, ListingFeature } from "../types/listing"

/**
 * Evidence-backed discovery data checked against the branch-specific source URL.
 *
 * This file is intentionally explicit. Do not infer occasions from age limits,
 * private hire from the word "private", or booking features from generic venue
 * descriptions. Unknown values stay null/empty until a source supports them.
 */
const auditedBySlug: Record<string, Partial<Listing>> = {
  "act-your-rage-therapies-par": {
    activities: ["rage-room"],
    occasions: ["birthdays"],
    price: 50,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "From £50 per room for two people; a three-person room is £60.",
    onlineBooking: true,
    bookingUrl: "https://actyourragetherapies.simplybook.it/v2/",
    sessionLengths: [30],
    groupSizeMin: 2,
    groupSizeMax: 3,
    sessionDurationType: "published-session",
  },
  "all-the-rage-birmingham": {
    activities: ["rage-room", "paint-splatter"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    onlineBooking: true,
    bookingUrl: "https://wannabook.online/booking/alltherage",
    ageMin: 10,
    sessionLengths: [30],
    groupSizeMin: 1,
    groupSizeMax: 4,
    accessibility: true,
    minimumAgeNote: "Minimum age 10; under-18s must be accompanied by an adult.",
    sessionDurationType: "total-booking",
    sessionDurationNote: "30 minutes total: 10-minute briefing/PPE, 15-minute smash and 5-minute decompression.",
  },
  "all-the-rage-scarborough": {
    activities: ["rage-room", "paint-splatter"],
    occasions: ["birthdays"],
    price: 35,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "From £35 for a solo room; duo £50 and trio £60.",
    onlineBooking: true,
    bookingUrl: "https://alltheragescarborough.simplybook.it/v2/",
    groupSizeMin: 1,
    groupSizeMax: 3,
  },
  "anger-issues-rage-rooms-ltd-ellesmere-port": {
    activities: ["rage-room"],
    occasions: ["birthdays", "corporate-team-building"],
    bookingUrl: "https://www.picktime.com/f063be23-77e0-4c6a-84a7-6785114f0c92",
    price: 35,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "From £35 per room for one person.",
    ageMin: 10,
    minimumAgeNote: "Minimum age 10; under-18s must be accompanied by an adult.",
    sessionLengths: [30],
    sessionDurationType: "activity-time",
    sessionDurationNote: "30 minutes in the rage room, plus 15 minutes for preparation and briefing.",
    onlineBooking: true,
  },
  "angry-smash-ltd-southend-on-sea": {
    activities: ["rage-room", "car-smash"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building", "families", "kids"],
    bookingUrl: "https://angrysmash.simplybook.it/",
    price: 45,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Junior smash sessions (ages 12–14) start at £45; adult solo sessions start at £60.",
    ageMin: 12,
    minimumAgeNote: "Junior sessions are for ages 12–14; adult sessions are 15+ and under-18s require an adult.",
    sessionLengths: [30],
    sessionDurationType: "published-session",
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
  },
  "arcadia-rage-room-darlington": {
    activities: ["rage-room", "paint-splatter", "vr"],
    occasions: [],
    price: null,
    priceNote: null,
    ageMin: 10,
    minimumAgeNote: "The published rage-room minimum age is 10.",
    onlineBooking: true,
  },
  "axed-and-enraged": {
    activities: ["rage-room", "axe-throwing"],
    occasions: [],
    price: 75,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "Rage-room packages start at £75 for up to two people.",
    onlineBooking: true,
    bookingUrl: "https://www.axedandenraged.co.uk/rage-room",
    giftVouchers: true,
    sessionLengths: [30],
    sessionDurationType: "published-session",
  },
  "destroyd-rage-rooms-northampton": {
    activities: ["rage-room", "escape-room"],
    occasions: [],
    price: 55,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "£55 for the published two-person rage-room session.",
    giftVouchers: true,
    sessionLengths: [30],
    sessionDurationType: "published-session",
  },
  "down-range-rage-room-gosport": {
    activities: ["rage-room", "axe-throwing"],
    occasions: [],
    price: null,
    priceNote: null,
    ageMin: 13,
    minimumAgeNote: "Ages 13–16 require a participating adult; ages 16–17 require an adult to sign waivers.",
    sessionLengths: [30],
    sessionDurationType: "activity-time",
    sessionDurationNote: "The booking slot is one hour and includes 30 minutes of smash time.",
    groupSizeMin: 1,
    groupSizeMax: 4,
    groupSizeNote: "Up to four may book; only two participate in the rage room at a time.",
    onlineBooking: true,
  },
  "game-vault-ayrshire-kilmarnock": {
    activities: ["rage-room", "escape-room", "vr"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    bookingUrl: "https://gamevaultayrshire.com/rage-room/",
    price: 17,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "The official six-player package publishes a £17 per-person cost; solo sessions are £25.",
    minimumAgeNote: "Minimum age 13 with an accompanying adult; solo entry is 18+.",
    ageMin: 13,
    sessionLengths: [15, 30, 60],
    groupSizeMin: 1,
    groupSizeMax: 10,
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
    sessionDurationType: "activity-time",
    groupSizeNote: "Bookings support up to 10 people, but only one person enters the rage room at a time.",
  },
  "go-rage-birmingham-rage-room-birmingham": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    onlineBooking: true,
    sessionLengths: [30],
    sessionDurationType: "published-session",
  },
  "hatchet-harrys-rage-room-derby": {
    activities: ["rage-room", "axe-throwing"],
    occasions: [],
    price: 36,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Rage-room sessions are £36 per person.",
    onlineBooking: true,
    giftVouchers: true,
    sessionLengths: [60],
    sessionDurationType: "published-session",
  },
  "hatchet-harrys-rage-room-liverpool": {
    activities: ["rage-room", "axe-throwing"],
    occasions: [],
    price: 36,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Rage-room sessions are £36 per person.",
    onlineBooking: true,
    giftVouchers: true,
    sessionLengths: [60],
    sessionDurationType: "published-session",
  },
  "house-of-rage-rage-room-leicester": {
    activities: ["rage-room", "axe-throwing"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    price: null,
    priceNote: null,
    onlineBooking: true,
  },
  "just-rage-rooms-henlow": {
    activities: ["rage-room"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building", "families"],
    price: 25,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "From £25 per person for a four-person booking; solo sessions are £35.",
    ageMin: 10,
    minimumAgeNote: "Minimum age 10; under-18s must be accompanied by an adult.",
    sessionLengths: [20, 30, 45, 55],
    sessionDurationType: "total-booking",
    sessionDurationNote: "Published durations include preparation/briefing; smash time varies by group size.",
    groupSizeMin: 1,
    groupSizeMax: null,
    groupSizeNote: "Standard packages cover one to four people; bespoke group packages are offered for 5+.",
    onlineBooking: true,
    corporatePackages: true,
  },
  "mission-classified-rage-room-grimsby": {
    activities: ["rage-room", "escape-room"],
    occasions: [],
    price: null,
    priceNote: null,
    giftVouchers: true,
  },
  "players-the-rage-rooms-brighton": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    ageMin: 18,
    minimumAgeNote: "Over-18s only; the venue states there are no exceptions.",
    sessionLengths: [15],
    sessionDurationType: "activity-time",
    sessionDurationNote: "15 minutes of smash time.",
    groupSizeMin: 1,
    groupSizeMax: 2,
    onlineBooking: true,
  },
  "rage-cage-uk-croydon": {
    activities: ["rage-room", "paint-splatter"],
    occasions: [],
    price: null,
    priceNote: null,
    giftVouchers: true,
  },
  "rage-it-out-consett": {
    activities: ["rage-room", "axe-throwing"],
    occasions: [],
    price: null,
    priceNote: null,
    onlineBooking: true,
    giftVouchers: true,
  },
  "rage-out-maidstone-maidstone": {
    activities: ["rage-room", "axe-throwing"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building", "date-nights", "families", "kids"],
    bookingUrl: "https://rage-out.venuebookr.com/",
    price: 40,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "Rage-room bookings start at £40 per room for the bring-your-own-items package.",
    ageMin: 8,
    minimumAgeNote: "Rage rooms require age 8+ and minimum height 1.2m.",
    walkInsAccepted: true,
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
    privateHire: true,
  },
  "rage-remedies-romford": {
    activities: ["rage-room", "axe-throwing"],
    occasions: ["corporate-team-building", "date-nights"],
    bookingUrl: "https://www.rageremedies.co.uk/book-online",
    price: 30,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "Rage-room bookings start at £30 for a room of up to two people.",
    ageMin: 10,
    minimumAgeNote: "All rage-room participants must be age 10+.",
    onlineBooking: true,
    corporatePackages: true,
    sessionLengths: [30, 45, 60],
    sessionDurationType: "published-session",
  },
  "rage-remedy-margate": {
    activities: ["rage-room"],
    occasions: ["birthdays"],
    price: null,
    priceNote: null,
    onlineBooking: true,
    giftVouchers: true,
  },
  "rage-room-birmingham-birmingham": {
    activities: ["rage-room"],
    occasions: ["birthdays"],
    price: null,
    priceNote: null,
    onlineBooking: true,
    giftVouchers: true,
  },
  "rage-room-hull": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    onlineBooking: true,
  },
  "rage-room-leicester": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    giftVouchers: true,
  },
  "rage-rooms-leamington-spa-royal-leamington-spa": {
    activities: ["rage-room", "paint-splatter"],
    occasions: ["birthdays", "corporate-team-building", "date-nights", "families", "kids"],
    price: null,
    priceNote: null,
    ageMin: 8,
    minimumAgeNote: "Ages 8+ may participate; ages 8–10 do not use weapons and under-18s require an adult on site.",
    sessionLengths: [10, 20],
    sessionDurationType: "activity-time",
    sessionDurationNote: "Solo rage time is 10 minutes and pair rage time is 20 minutes, plus 10 minutes for briefing/PPE.",
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
  },
  "rage-rooms-norwich-norwich": {
    activities: ["rage-room", "paint-splatter", "mobile-rage-room"],
    occasions: ["hen-parties", "stag-parties", "families", "kids"],
    price: null,
    priceNote: null,
    packages: null,
    bookingUrl: "https://ragerooms-norwich.co.uk/rooms/rage-rooms/",
    ageMin: 6,
    sessionLengths: [60],
    groupSizeMin: 1,
    groupSizeMax: 4,
    minimumAgeNote: "Child sessions start at age 6 with lighter equipment; adult sessions are age 10+.",
    onlineBooking: true,
    giftVouchers: true,
    sessionDurationType: "total-booking",
    sessionDurationNote: "The one-hour booking slot includes briefing, PPE and shared smash time.",
  },
  "rage-x-treme-polegate": {
    activities: ["rage-room", "axe-throwing"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    description: "Polegate rage-room and axe-throwing venue with 30-minute rage packages for individuals and groups. Supplied-item and bring-your-own options are available, with PPE and supervision provided.",
    price: 19.5,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Bring-your-own rage-room sessions start at £19.50 per person; supplied-item packages start at £29.50.",
    ageMin: 8,
    minimumAgeNote: "Minimum age 8; ages 8–12 must participate with a paying adult.",
    sessionLengths: [30],
    sessionDurationType: "activity-time",
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
    privateHire: true,
    accessibility: true,
  },
  "raging-bath": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    onlineBooking: true,
    giftVouchers: true,
  },
  "smash-it-huddersfield": {
    activities: ["rage-room"],
    occasions: ["hen-parties", "stag-parties"],
    price: 60,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "£60 per room for up to two people.",
    ageMin: 8,
    minimumAgeNote: "The smash-room minimum age is 8.",
    walkInsAccepted: false,
    onlineBooking: true,
    sessionLengths: [30],
    sessionDurationType: "activity-time",
    sessionDurationNote: "Up to 30 minutes of smash time.",
  },
  "smash-it-rage-room-ltd-london": {
    activities: ["rage-room"],
    occasions: [],
    price: null,
    priceNote: null,
    onlineBooking: true,
  },
  "smash-palace-lincoln": {
    activities: ["rage-room"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building", "date-nights"],
    price: 30,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Quick Smash sessions start at £30 per person.",
    sessionLengths: [15, 20, 25],
    sessionDurationType: "activity-time",
    walkInsAccepted: false,
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
    groupSizeMin: 1,
    groupSizeMax: 4,
  },
  "smash-space-uk-newcastle": {
    activities: ["rage-room", "escape-room"],
    occasions: ["birthdays"],
    bookingUrl: "https://smashspaceuk.resova.co.uk/",
    price: 49.99,
    priceCurrency: "GBP",
    priceUnit: "per-group",
    priceNote: "Rage-room bookings start at £49.99 per group for one or two participants.",
    ageMin: 4,
    minimumAgeNote: "The venue publishes rage-room sessions from age 4; check the selected package before booking.",
    groupSizeMin: 1,
    groupSizeMax: 4,
    onlineBooking: true,
    giftVouchers: true,
  },
  "the-break-rooms-leominster": {
    activities: ["rage-room"],
    occasions: ["birthdays", "families", "kids"],
    price: 40,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "£40 per room for up to two people; a third participant costs £10 extra.",
    ageMin: 12,
    sessionLengths: [20],
    groupSizeMin: 1,
    groupSizeMax: 3,
    walkInsAccepted: false,
    onlineBooking: true,
    sessionDurationType: "published-session",
  },
  "the-rabbit-hole-rage-room-swindon": {
    activities: ["rage-room"],
    occasions: ["hen-parties", "stag-parties"],
    price: null,
    priceNote: null,
  },
  "the-rage-house-newcastle-under-lyme": {
    activities: ["rage-room", "axe-throwing", "airsoft-target"],
    occasions: [],
    price: null,
    priceNote: null,
  },
  "the-smash-lab-wellingborough": {
    activities: ["rage-room"],
    occasions: ["birthdays", "corporate-team-building"],
    bookingUrl: null,
    price: 65,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "£65 per room for up to two people.",
    ageMin: 12,
    sessionLengths: [30],
    groupSizeMin: 1,
    groupSizeMax: 2,
    onlineBooking: null,
    corporatePackages: true,
    sessionDurationType: "published-session",
  },
  "the-snake-room-urban-axe-throwing-chesterfield": {
    activities: ["rage-room", "axe-throwing"],
    occasions: ["birthdays"],
    price: 50,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "£50 per room for up to two people.",
    onlineBooking: true,
    bookingUrl: "https://snakeroom.co.uk/booking/rageroom/",
    sessionLengths: [30],
    groupSizeMin: 1,
    groupSizeMax: 2,
    sessionDurationType: "activity-time",
  },
  "the-underground-newport": {
    activities: ["rage-room", "axe-throwing", "airsoft-target"],
    occasions: [],
    price: 30,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "Rage-room bookings start at £30 for one person; two people cost £50.",
    ageMin: 12,
    minimumAgeNote: "The rage-room booking page states ages 12+.",
    sessionLengths: [15],
    sessionDurationType: "activity-time",
    sessionDurationNote: "The booking occupies a 30-minute slot and includes 15 minutes of smash time.",
    groupSizeMin: 1,
    groupSizeMax: 2,
    onlineBooking: true,
  },
  "urban-xtreme-colchester-colchester": {
    activities: ["rage-room", "axe-throwing", "airsoft-target"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building", "date-nights", "families", "kids"],
    price: 34.99,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "Bronze rage-room packages start at £34.99 per person.",
    bookingUrl: "https://www.urbanxtreme.co.uk/rage-room-colchester/",
    ageMin: 8,
    sessionLengths: [30],
    groupSizeMin: 2,
    groupSizeMax: 8,
    minimumAgeNote: "Rage room minimum age is 8; under-18s require adult supervision. Airsoft is 12+.",
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
    privateHire: true,
    accessibility: true,
    sessionDurationType: "activity-time",
    sessionDurationNote: "30 minutes of smash time; the venue advises allowing about one hour overall.",
  },
  "venture-games-bedford-rage-room": {
    activities: ["rage-room", "paint-splatter"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    price: 60,
    priceCurrency: "GBP",
    priceUnit: "per-room",
    priceNote: "Rage Room 30 starts at £60 per room for one or two players.",
    bookingUrl: "https://www.venturegamesbedford.co.uk/rage-room/",
    ageMin: 12,
    sessionLengths: [30, 45, 60, 90],
    groupSizeMin: 1,
    groupSizeMax: 14,
    minimumAgeNote: "Minimum age 12; under-18s require an adult on site.",
    walkInsAccepted: null,
    onlineBooking: true,
    giftVouchers: true,
    sessionDurationType: "total-booking",
    sessionDurationNote: "Published durations include the safety briefing.",
  },
  "the-activity-dome-weston-super-mare": {
    activities: ["rage-room", "axe-throwing", "archery", "airsoft-target"],
    occasions: ["birthdays"],
    price: 24.5,
    priceCurrency: "GBP",
    priceUnit: "per-person",
    priceNote: "15-minute rage-room sessions start at £24.50 per person.",
    bookingUrl: "https://theactivitydome.com/book-now/?url=https%3A%2F%2Fwannabook.online%2Fbooking%2Fwestonrageroom",
    ageMin: 8,
    sessionLengths: [15, 30],
    minimumAgeNote: "The standard rage-room minimum age is 8; combined Throw Your Rage sessions are 12+.",
    onlineBooking: true,
    giftVouchers: true,
    accessibility: true,
    sessionDurationType: "activity-time",
    sessionDurationNote: "Published rage-room durations are shared among all participants; arrive 10 minutes early for waiver/PPE.",
  },
  "wreck-it-room-aberdeen": {
    activities: ["rage-room"],
    occasions: ["birthdays", "hen-parties", "stag-parties", "corporate-team-building"],
    ageMin: 8,
    minimumAgeNote: "Under-18 sessions are available from age 8 with adult supervision.",
    onlineBooking: true,
    giftVouchers: true,
    corporatePackages: true,
  },
}

const file = join(process.cwd(), "data", "listings.json")
const listings = JSON.parse(readFileSync(file, "utf8")) as Listing[]

const missingAudits = listings.filter((listing) => !auditedBySlug[listing.slug ?? ""])
if (missingAudits.length > 0) {
  throw new Error(`Missing explicit audit data for: ${missingAudits.map((listing) => listing.slug).join(", ")}`)
}

const resetUnknowns: Partial<Listing> = {
  activities: ["rage-room"],
  occasions: [],
  bookingUrl: null,
  price: null,
  priceNote: null,
  priceCurrency: null,
  priceUnit: null,
  ageMin: null,
  minimumAgeNote: null,
  sessionLengths: null,
  sessionDurationType: null,
  sessionDurationNote: null,
  groupSizeMin: null,
  groupSizeMax: null,
  groupSizeNote: null,
  packages: null,
  walkInsAccepted: null,
  onlineBooking: null,
  giftVouchers: null,
  corporatePackages: null,
  privateHire: null,
  accessibility: null,
  rating: null,
  reviewCount: null,
}

const audited = listings.map((listing) => {
  const result = {
    ...listing,
    ...resetUnknowns,
    ...auditedBySlug[listing.slug ?? ""],
    lastVerified: "2026-08-19",
  } as Listing
  const evidenceFeatures = new Set<ListingFeature>()
  if (["rage-out-maidstone-maidstone", "rage-x-treme-polegate"].includes(result.slug ?? "")) {
    evidenceFeatures.add("byo-smashables")
  }
  if (result.occasions?.includes("corporate-team-building")) evidenceFeatures.add("corporate-groups")
  if (result.occasions?.includes("birthdays")) evidenceFeatures.add("birthday-parties")
  if (result.occasions?.some((occasion) => occasion === "hen-parties" || occasion === "stag-parties")) {
    evidenceFeatures.add("hen-stag-parties")
  }
  if (result.occasions?.includes("date-nights")) evidenceFeatures.add("couples")
  if (result.activities?.includes("mobile-rage-room")) evidenceFeatures.add("mobile-experience")
  if (result.accessibility === true) evidenceFeatures.add("accessible-venue")
  result.features = Array.from(evidenceFeatures)
  return result
})

writeFileSync(file, `${JSON.stringify(audited, null, 2)}\n`)
console.log(`Applied explicit evidence-backed discovery data to ${audited.length} listings.`)
